version: '3'

services:
  php-fpm:
    depends_on:
      - db
    build:
      context: ./php-fpm
    restart: always
    volumes:
      - ../src:/var/www
      - ./php-fpm/php.ini:/usr/local/etc/php/conf.d/custom.ini

  nginx:
    depends_on: 
      - php-fpm
    restart: always
    build:
      context: ./nginx
    volumes:
      - ../src:/var/www
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites/:/etc/nginx/sites-available
      - ./nginx/conf.d/:/etc/nginx/conf.d
    ports:
      - "80:80"
  
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=3a10a39d21b304cc29097b8fe2569939
    volumes:
      - ./createschema.sql:/docker-entrypoint-initdb.d/1-createschema.sql
  
  dbadm:
    depends_on:
      - db
    image: adminer
    restart: always
    ports:
      - "127.5.0.1:3080:8080"

  szerviz:
    build:
      context: ./szerviz
    volumes:
      - ../src:/usr/src
  
  